import { useMemo, useState } from 'react';
import { ArrowLeft, Check, Clipboard, Dices, Play } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import type { ClientMessage } from '../protocol/messages';
import type { ClientConfig } from '../state/types';
import { DEFAULT_FONT_FAMILY, DEFAULT_FONT_WEIGHT } from '../hooks/useFontLoader';
import { SHADER_EFFECTS, PANE_SWITCH_EFFECTS } from '../lib/terminalFxShaders';
import { WALLPAPER_SHADERS } from '../lib/wallpaperCatalog';
import { DEFAULT_THEME } from '../state/defaultTheme';
import { useStore } from '../state/store';
import { TerminalShaderPreview } from './TerminalShaderPreview';
import { Button } from './ui/button';
import { Field, FieldContent, FieldGroup, FieldLabel, FieldLegend, FieldSet } from './ui/field';
import { Input } from './ui/input';
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Slider } from './ui/slider';
import { Switch } from './ui/switch';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';
import { Textarea } from './ui/textarea';

interface Props {
  config: ClientConfig;
  send: (message: ClientMessage) => void;
}

type Draft = {
  colors: string;
  fontFamily: string;
  fontWeight: number;
  fontSize: number;
  animations: boolean;
  wallpaper: string;
  wallpaperShader: string;
  wallpaperOpacity: number;
  wallpaperBlur: number;
  wallpaperSaturate: number;
  wallpaperSpeed: number;
  wallpaperSeed: string;
  wallpaperFollowsMouse: boolean;
  wallpaperFollowsKeyboard: boolean;
  shader: string;
  paneSwitchShader: string;
  paneSwitchIntensity: number;
  paneSwitchDuration: number;
};

const SEED_ADJECTIVES = [
  'ancient',
  'brisk',
  'cosmic',
  'electric',
  'fuzzy',
  'luminous',
  'mellow',
  'neon',
  'quiet',
  'velvet',
  'wandering',
  'wobbly',
];

const SEED_NOUNS = [
  'badger',
  'circuit',
  'comet',
  'fjord',
  'lantern',
  'mushroom',
  'nebula',
  'orbit',
  'pancake',
  'sprocket',
  'teapot',
  'volcano',
];

const SEED_ENDINGS = [
  'cascade',
  'disco',
  'dream',
  'engine',
  'glitch',
  'monsoon',
  'parade',
  'signal',
  'soup',
  'storm',
  'tango',
  'whisper',
];

function randomItem(words: string[]): string {
  const value = new Uint32Array(1);
  crypto.getRandomValues(value);
  return words[value[0] % words.length];
}

function generateWallpaperSeed(): string {
  return [randomItem(SEED_ADJECTIVES), randomItem(SEED_NOUNS), randomItem(SEED_ENDINGS)].join('-');
}

function initialDraft(config: ClientConfig): Draft {
  return {
    colors: config.active_color_scheme ?? '',
    fontFamily: config.terminal.fontFamily ?? DEFAULT_FONT_FAMILY,
    fontWeight: config.terminal.fontWeight ?? DEFAULT_FONT_WEIGHT,
    fontSize: config.terminal.fontSize ?? 18,
    animations: config.animations,
    wallpaper: config.wallpaper ?? '',
    wallpaperShader: config.wallpaper_shader ?? '',
    wallpaperOpacity: config.wallpaper_opacity ?? 0.2,
    wallpaperBlur: config.wallpaper_blur ?? 0,
    wallpaperSaturate: config.wallpaper_saturate ?? 1,
    wallpaperSpeed: config.wallpaper_speed,
    wallpaperSeed: config.wallpaper_seed,
    wallpaperFollowsMouse: config.wallpaper_shader_follows_mouse_cursor,
    wallpaperFollowsKeyboard: config.wallpaper_shader_follows_keyboard_input,
    shader: config.shader ?? '',
    paneSwitchShader: config.pane_switch_shader ?? '',
    paneSwitchIntensity: config.pane_switch_intensity,
    paneSwitchDuration: config.pane_switch_duration,
  };
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function toToml(draft: Draft): string {
  const lines = [
    '# Styling settings generated by btmux /config',
    `animations = ${draft.animations}`,
    draft.colors ? `colors = ${quote(draft.colors)}` : null,
    draft.wallpaper ? `wallpaper = ${quote(draft.wallpaper)}` : null,
    draft.wallpaperShader ? `wallpaper-shader = ${quote(draft.wallpaperShader)}` : null,
    `wallpaper-opacity = ${draft.wallpaperOpacity.toFixed(2)}`,
    `wallpaper-blur = ${draft.wallpaperBlur.toFixed(1)}`,
    `wallpaper-saturate = ${draft.wallpaperSaturate.toFixed(2)}`,
    `wallpaper-speed = ${draft.wallpaperSpeed.toFixed(2)}`,
    `wallpaper-seed = ${quote(draft.wallpaperSeed)}`,
    `wallpaper-shader-follows-mouse-cursor = ${draft.wallpaperFollowsMouse}`,
    `wallpaper-shader-follows-keyboard-input = ${draft.wallpaperFollowsKeyboard}`,
    draft.shader ? `shader = ${quote(draft.shader)}` : null,
    draft.paneSwitchShader ? `pane-switch-shader = ${quote(draft.paneSwitchShader)}` : null,
    `pane-switch-intensity = ${draft.paneSwitchIntensity.toFixed(2)}`,
    `pane-switch-duration = ${draft.paneSwitchDuration.toFixed(2)}`,
    '',
    '[terminal]',
    `font-family = ${quote(draft.fontFamily)}`,
    `font-size = ${draft.fontSize.toFixed(1)}`,
    `font-weight = ${draft.fontWeight}`,
  ];
  return lines.filter((line) => line !== null).join('\n');
}

function RangeField({
  label,
  value,
  min,
  max,
  step,
  onChange,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  onChange: (value: number) => void;
}) {
  return (
    <Field>
      <div className="flex items-center justify-between gap-4">
        <FieldLabel>{label}</FieldLabel>
        <output className="tabular-nums text-sm text-muted-foreground">{value.toFixed(step < 1 ? 2 : 0)}</output>
      </div>
      <Slider value={[value]} min={min} max={max} step={step} onValueChange={([next]) => onChange(next)} />
    </Field>
  );
}

export function ConfigPage({ config, send }: Props) {
  const navigate = useNavigate();
  const allSessions = useStore((state) => state.allSessions);
  const [draft, setDraft] = useState(() => initialDraft(config));
  const [copied, setCopied] = useState(false);
  const [paneSwitchPreviewKey, setPaneSwitchPreviewKey] = useState(0);
  const toml = useMemo(() => toToml(draft), [draft]);

  const update = <K extends keyof Draft>(key: K, value: Draft[K], wire: Record<string, unknown>) => {
    setDraft((current) => ({ ...current, [key]: value }));
    send({ type: 'update_config', update: wire });
  };

  const copy = async () => {
    await navigator.clipboard.writeText(toml);
    setCopied(true);
    toast.success('Settings copied to clipboard');
    window.setTimeout(() => setCopied(false), 1600);
  };

  const font = config.fonts.find((item) => item.family === draft.fontFamily);
  const weightMin = font?.weight_min ?? 100;
  const weightMax = font?.weight_max ?? 900;

  const goBack = () => {
    const lastSessionName = sessionStorage.getItem('btmux-last-session');
    const session = allSessions.find((item) => item.name === lastSessionName) ?? allSessions[0];
    if (!session) {
      navigate('/', { replace: true });
      return;
    }

    const activeWindow = session.windows[session.active_window];
    const target = activeWindow
      ? `/s/${encodeURIComponent(session.name)}/w/${encodeURIComponent(activeWindow.name)}`
      : `/s/${encodeURIComponent(session.name)}`;
    navigate(target, { replace: true });
  };

  return (
    <main className="relative h-full overflow-y-auto bg-transparent text-foreground">
      <header className="sticky top-0 border-b bg-background/95 backdrop-blur">
        <div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-4 px-4 py-3 md:px-8">
          <div className="flex min-w-0 items-center gap-3">
            <Button variant="ghost" size="icon" onClick={goBack} aria-label="Go back" title="Go back">
              <ArrowLeft />
            </Button>
            <div className="hidden min-w-0 sm:block">
              <h1 className="truncate text-base font-semibold">Appearance config</h1>
              <p className="truncate text-xs text-muted-foreground">Live session preview</p>
            </div>
          </div>
          <Button onClick={copy}>
            {copied ? <Check data-icon="inline-start" /> : <Clipboard data-icon="inline-start" />}
            {copied ? 'Copied' : 'Copy settings to clipboard'}
          </Button>
        </div>
      </header>

      <div className="mx-auto grid max-w-7xl gap-8 px-4 py-8 lg:grid-cols-[minmax(0,1fr)_minmax(320px,0.8fr)] lg:px-8">
        <Tabs defaultValue="wallpaper" className="min-w-0">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="wallpaper">Wallpaper</TabsTrigger>
            <TabsTrigger value="terminal">Terminal</TabsTrigger>
            <TabsTrigger value="effects">Effects</TabsTrigger>
          </TabsList>

          <TabsContent value="wallpaper" className="pt-6">
            <FieldGroup>
              <FieldSet>
                <FieldLegend>Wallpaper source</FieldLegend>
                <FieldGroup>
                  <Field>
                    <FieldLabel htmlFor="wallpaper-shader">Procedural shader</FieldLabel>
                    <Select
                      value={draft.wallpaperShader || 'none'}
                      onValueChange={(value) =>
                        update('wallpaperShader', value === 'none' ? '' : value, {
                          wallpaper_shader: value === 'none' ? '' : value,
                        })
                      }
                    >
                      <SelectTrigger id="wallpaper-shader" className="w-full">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectGroup>
                          <SelectItem value="none">None</SelectItem>
                          {WALLPAPER_SHADERS.map((item) => (
                            <SelectItem key={item.id} value={item.id}>
                              {item.label}
                            </SelectItem>
                          ))}
                        </SelectGroup>
                      </SelectContent>
                    </Select>
                  </Field>
                  <Field>
                    <FieldLabel htmlFor="wallpaper-url">Image URL or path</FieldLabel>
                    <Input
                      id="wallpaper-url"
                      value={draft.wallpaper}
                      onChange={(event) => setDraft((current) => ({ ...current, wallpaper: event.target.value }))}
                      onBlur={() => send({ type: 'update_config', update: { wallpaper: draft.wallpaper } })}
                      placeholder="https://… or ~/Pictures/wallpaper.png"
                    />
                  </Field>
                  <RangeField
                    label="Opacity"
                    value={draft.wallpaperOpacity}
                    min={0}
                    max={1}
                    step={0.01}
                    onChange={(value) => update('wallpaperOpacity', value, { wallpaper_opacity: value })}
                  />
                  <RangeField
                    label="Blur"
                    value={draft.wallpaperBlur}
                    min={0}
                    max={50}
                    step={1}
                    onChange={(value) => update('wallpaperBlur', value, { wallpaper_blur: value })}
                  />
                  <RangeField
                    label="Saturation"
                    value={draft.wallpaperSaturate}
                    min={0}
                    max={1}
                    step={0.01}
                    onChange={(value) => update('wallpaperSaturate', value, { wallpaper_saturate: value })}
                  />
                  <RangeField
                    label="Animation speed"
                    value={draft.wallpaperSpeed}
                    min={0}
                    max={10}
                    step={0.05}
                    onChange={(value) => update('wallpaperSpeed', value, { wallpaper_speed: value })}
                  />
                  <Field>
                    <FieldLabel htmlFor="wallpaper-seed">Seed</FieldLabel>
                    <div className="flex items-center gap-2">
                      <Input
                        id="wallpaper-seed"
                        className="min-w-0"
                        value={draft.wallpaperSeed}
                        onChange={(event) => setDraft((current) => ({ ...current, wallpaperSeed: event.target.value }))}
                        onBlur={() => send({ type: 'update_config', update: { wallpaper_seed: draft.wallpaperSeed } })}
                      />
                      <Button
                        type="button"
                        variant="outline"
                        onClick={() => {
                          const seed = generateWallpaperSeed();
                          update('wallpaperSeed', seed, { wallpaper_seed: seed });
                        }}
                      >
                        <Dices data-icon="inline-start" />
                        Generate
                      </Button>
                    </div>
                  </Field>
                  <Field orientation="horizontal">
                    <FieldContent>
                      <FieldLabel htmlFor="wallpaper-follows-mouse">Follow mouse cursor</FieldLabel>
                    </FieldContent>
                    <Switch
                      id="wallpaper-follows-mouse"
                      checked={draft.wallpaperFollowsMouse}
                      onCheckedChange={(value) =>
                        update('wallpaperFollowsMouse', value, { wallpaper_shader_follows_mouse_cursor: value })
                      }
                    />
                  </Field>
                  <Field orientation="horizontal">
                    <FieldContent>
                      <FieldLabel htmlFor="wallpaper-follows-keyboard">Follow keyboard input</FieldLabel>
                    </FieldContent>
                    <Switch
                      id="wallpaper-follows-keyboard"
                      checked={draft.wallpaperFollowsKeyboard}
                      onCheckedChange={(value) =>
                        update('wallpaperFollowsKeyboard', value, { wallpaper_shader_follows_keyboard_input: value })
                      }
                    />
                  </Field>
                </FieldGroup>
              </FieldSet>
            </FieldGroup>
          </TabsContent>

          <TabsContent value="terminal" className="pt-6">
            <FieldGroup>
              <Field>
                <FieldLabel htmlFor="color-scheme">Color scheme</FieldLabel>
                <Select
                  value={draft.colors || 'none'}
                  onValueChange={(value) =>
                    update('colors', value === 'none' ? '' : value, { colors: value === 'none' ? '' : value })
                  }
                >
                  <SelectTrigger id="color-scheme" className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectGroup>
                      <SelectItem value="none">Built-in default</SelectItem>
                      {config.color_schemes.map((scheme) => (
                        <SelectItem key={scheme} value={scheme}>
                          {scheme}
                        </SelectItem>
                      ))}
                    </SelectGroup>
                  </SelectContent>
                </Select>
              </Field>
              <Field>
                <FieldLabel htmlFor="font-family">Font family</FieldLabel>
                <Select
                  value={draft.fontFamily}
                  onValueChange={(value) => {
                    const nextFont = config.fonts.find((item) => item.family === value);
                    const nextWeight = Math.min(
                      nextFont?.weight_max ?? 900,
                      Math.max(nextFont?.weight_min ?? 100, draft.fontWeight),
                    );
                    setDraft((current) => ({ ...current, fontFamily: value, fontWeight: nextWeight }));
                    send({ type: 'update_config', update: { font_family: value, font_weight: nextWeight } });
                  }}
                >
                  <SelectTrigger id="font-family" className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectGroup>
                      {config.fonts.map((item) => (
                        <SelectItem key={item.family} value={item.family}>
                          {item.family}
                        </SelectItem>
                      ))}
                    </SelectGroup>
                  </SelectContent>
                </Select>
              </Field>
              <RangeField
                label="Font size"
                value={draft.fontSize}
                min={8}
                max={36}
                step={1}
                onChange={(value) => update('fontSize', value, { font_size: value })}
              />
              <RangeField
                label="Font weight"
                value={draft.fontWeight}
                min={weightMin}
                max={weightMax}
                step={100}
                onChange={(value) => update('fontWeight', value, { font_weight: value })}
              />
              <Field orientation="horizontal">
                <FieldContent>
                  <FieldLabel htmlFor="animations">Animations</FieldLabel>
                </FieldContent>
                <Switch
                  id="animations"
                  checked={draft.animations}
                  onCheckedChange={(value) => update('animations', value, { animations: value })}
                />
              </Field>
            </FieldGroup>
          </TabsContent>

          <TabsContent value="effects" className="pt-6">
            <FieldGroup>
              <Field>
                <FieldLabel htmlFor="shader">Terminal shader</FieldLabel>
                <Select
                  value={draft.shader || 'none'}
                  onValueChange={(value) =>
                    update('shader', value === 'none' ? '' : value, { shader: value === 'none' ? '' : value })
                  }
                >
                  <SelectTrigger id="shader" className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectGroup>
                      <SelectItem value="none">None</SelectItem>
                      {SHADER_EFFECTS.map((item) => (
                        <SelectItem key={item.id} value={item.id}>
                          {item.label}
                        </SelectItem>
                      ))}
                    </SelectGroup>
                  </SelectContent>
                </Select>
              </Field>
              <Field>
                <FieldLabel htmlFor="pane-switch-shader">Pane-switch shader</FieldLabel>
                <Select
                  value={draft.paneSwitchShader || 'default'}
                  onValueChange={(value) => {
                    update('paneSwitchShader', value === 'default' ? '' : value, {
                      pane_switch_shader: value === 'default' ? '' : value,
                    });
                    setPaneSwitchPreviewKey((key) => key + 1);
                  }}
                >
                  <SelectTrigger id="pane-switch-shader" className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectGroup>
                      <SelectItem value="default">Default</SelectItem>
                      {PANE_SWITCH_EFFECTS.map((item) => (
                        <SelectItem key={item.id} value={item.id}>
                          {item.label}
                        </SelectItem>
                      ))}
                    </SelectGroup>
                  </SelectContent>
                </Select>
              </Field>
              <RangeField
                label="Pane-switch intensity"
                value={draft.paneSwitchIntensity}
                min={0}
                max={3}
                step={0.05}
                onChange={(value) => {
                  update('paneSwitchIntensity', value, { pane_switch_intensity: value });
                  setPaneSwitchPreviewKey((key) => key + 1);
                }}
              />
              <RangeField
                label="Pane-switch duration"
                value={draft.paneSwitchDuration}
                min={0.1}
                max={5}
                step={0.05}
                onChange={(value) => {
                  update('paneSwitchDuration', value, { pane_switch_duration: value });
                  setPaneSwitchPreviewKey((key) => key + 1);
                }}
              />
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => setPaneSwitchPreviewKey((key) => key + 1)}
              >
                <Play data-icon="inline-start" />
                Replay pane-switch effect
              </Button>
            </FieldGroup>
          </TabsContent>
        </Tabs>

        <aside className="min-w-0">
          <div className="sticky top-24 flex flex-col gap-3">
            <div className="overflow-hidden rounded-md border bg-card shadow-sm">
              <div className="flex items-center gap-2 border-b px-4 py-2 text-xs text-muted-foreground">
                <span className="size-2 rounded-full bg-theme-red" />
                <span className="size-2 rounded-full bg-theme-yellow" />
                <span className="size-2 rounded-full bg-theme-green" />
                <span className="ml-2">btmux preview</span>
              </div>
              <TerminalShaderPreview
                shaderId={draft.shader}
                paneSwitchShaderId={draft.paneSwitchShader}
                paneSwitchIntensity={draft.paneSwitchIntensity}
                paneSwitchDuration={draft.paneSwitchDuration}
                paneSwitchPreviewKey={paneSwitchPreviewKey}
                theme={config.theme ?? DEFAULT_THEME}
                fontFamily={draft.fontFamily}
                fontWeight={draft.fontWeight}
                fontSize={draft.fontSize}
                animations={draft.animations}
              />
            </div>
            <Field>
              <FieldLabel htmlFor="toml-output">Generated TOML</FieldLabel>
              <Textarea id="toml-output" readOnly value={toml} className="min-h-72 resize-none font-mono text-xs" />
            </Field>
          </div>
        </aside>
      </div>
    </main>
  );
}
