#!/usr/bin/env node

import { execFileSync } from 'node:child_process';
import { cpSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, join, resolve } from 'node:path';
import ts from '../frontend/node_modules/typescript/lib/typescript.js';

const REPOSITORY = 'https://github.com/pbakaus/radiant.git';
const REVISION = 'e5d078d1b26e11224ec781ffdc9506a7faf19a4a';
const workspace = resolve(import.meta.dirname, '..');
const suppliedSource = process.argv[2];
const temporary = suppliedSource ? null : mkdtempSync(join(tmpdir(), 'btmux-radiant-'));
const sourceRoot = suppliedSource ? resolve(suppliedSource) : join(temporary, 'radiant');
const outputRoot = join(workspace, 'frontend/public/radiant');

const BRIDGE = `<style>.label{display:none!important}</style>
<script>
(function(){
  var nativeRaf=window.requestAnimationFrame.bind(window), enabled=true, speed=1, maxFps=30, epoch=performance.now(), virtualEpoch=epoch, pending=null, lastFrame=-Infinity;
  var seed=new URLSearchParams(location.search).get('seed')||'btmux', hash=2166136261;
  for(var i=0;i<seed.length;i++){hash^=seed.charCodeAt(i);hash=Math.imul(hash,16777619)}
  Math.random=function(){hash+=0x6D2B79F5;var t=hash;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296};
  window.requestAnimationFrame=function(callback){
    if(!enabled){pending=callback;return 0}
    function tick(now){
      if(!enabled){pending=callback;return}
      if(now-lastFrame<(1000/maxFps)-1){nativeRaf(tick);return}
      lastFrame=now;callback(virtualEpoch+(now-epoch)*speed)
    }
    return nativeRaf(tick)
  };
  addEventListener('message',function(event){var data=event.data;if(!data)return;
    if(data.type==='btmux-runtime'){virtualEpoch+=(performance.now()-epoch)*speed;epoch=performance.now();var wasEnabled=enabled;enabled=data.animated;speed=data.speed;maxFps=Math.max(1,data.maxFps||30);if(enabled&&!wasEnabled&&pending){var callback=pending;pending=null;lastFrame=-Infinity;window.requestAnimationFrame(callback)}return}
    if(data.type!=='btmux-pointer')return;
    var canvas=document.querySelector('canvas');if(!canvas)return;
    if(!data.active){canvas.dispatchEvent(new MouseEvent('mouseleave'));return}
    var rect=canvas.getBoundingClientRect();canvas.dispatchEvent(new MouseEvent('mousemove',{clientX:rect.left+data.x*rect.width,clientY:rect.top+data.y*rect.height,bubbles:true}));
  });
})();
</script>`;

function literal(node) {
  if (ts.isStringLiteral(node)) return node.text;
  if (ts.isNumericLiteral(node)) return Number(node.text);
  if (node.kind === ts.SyntaxKind.TrueKeyword) return true;
  if (node.kind === ts.SyntaxKind.FalseKeyword) return false;
  if (ts.isArrayLiteralExpression(node)) return node.elements.map(literal);
  if (ts.isObjectLiteralExpression(node)) {
    return Object.fromEntries(node.properties.filter(ts.isPropertyAssignment).map((property) => [property.name.text, literal(property.initializer)]));
  }
  return undefined;
}

function readCatalog(path) {
  const source = ts.createSourceFile(path, readFileSync(path, 'utf8'), ts.ScriptTarget.Latest, true);
  for (const statement of source.statements) {
    if (!ts.isVariableStatement(statement)) continue;
    const declaration = statement.declarationList.declarations.find((item) => item.name.getText(source) === 'shaders');
    if (declaration?.initializer && ts.isArrayLiteralExpression(declaration.initializer)) return literal(declaration.initializer);
  }
  throw new Error('Could not find the Radiant shaders catalog');
}

try {
  if (!suppliedSource) {
    execFileSync('git', ['clone', '--quiet', REPOSITORY, sourceRoot]);
    execFileSync('git', ['-C', sourceRoot, 'checkout', '--quiet', REVISION]);
  }
  const actualRevision = execFileSync('git', ['-C', sourceRoot, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
  if (actualRevision !== REVISION) throw new Error(`Expected Radiant ${REVISION}, got ${actualRevision}`);

  const shaders = readCatalog(join(sourceRoot, 'src/lib/shaders.ts'));
  rmSync(outputRoot, { recursive: true, force: true });
  mkdirSync(outputRoot, { recursive: true });
  for (const shader of shaders) {
    const sourcePath = join(sourceRoot, 'static', shader.file);
    const html = readFileSync(sourcePath, 'utf8');
    if (!html.includes('</head>')) throw new Error(`${shader.file} has no </head>`);
    writeFileSync(join(outputRoot, basename(shader.file)), html.replace('</head>', `${BRIDGE}\n</head>`));
  }
  cpSync(join(sourceRoot, 'LICENSE'), join(outputRoot, 'LICENSE'));
  writeFileSync(join(outputRoot, 'REVISION'), `${actualRevision}\n`);

  const manifestPath = join(workspace, 'frontend/src/generated/radiantShaders.ts');
  mkdirSync(resolve(manifestPath, '..'), { recursive: true });
  const manifest = `// Generated by scripts/sync-radiant.mjs. Do not edit.\n` +
    `export const RADIANT_REVISION = ${JSON.stringify(actualRevision)};\n` +
    `export const RADIANT_SHADERS = ${JSON.stringify(shaders, null, 2)} as const;\n`;
  writeFileSync(manifestPath, manifest);
  console.log(`Vendored ${shaders.length} Radiant shaders at ${actualRevision}`);
} finally {
  if (temporary) rmSync(temporary, { recursive: true, force: true });
}
