import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const root = resolve(import.meta.dirname, "..");
const require = createRequire(resolve(root, "frontend/package.json"));
const components = [
  "Aurora",
  "Checkerboard",
  "FractalNoise",
  "GaborNoise",
  "Grid",
  "IsometricCubes",
  "LinearGradient",
  "Marble",
  "MeshGradient",
  "PerlinNoise",
  "Plasma",
  "RadialGradient",
  "SimplexNoise",
  "SineWave",
  "Strands",
  "Swirl",
  "Truchet",
  "Voronoi",
];
const kebab = (name) =>
  name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const catalog = [];
for (const name of components) {
  const { componentDefinition: definition } = await import(
    pathToFileURL(require.resolve(`shaders/core/${name}`))
  );
  const params = Object.entries(definition.props).map(([name, prop]) => {
    const ui = prop.ui ?? {};
    const value = prop.default;
    const kind =
      typeof value === "number"
        ? "number"
        : typeof value === "boolean"
          ? "boolean"
          : ui.type === "select"
            ? "select"
            : ui.type === "color"
              ? "color"
              : typeof value === "string"
                ? "text"
                : ui.type === "position"
                  ? "position"
                  : "json";
    return {
      name,
      key: kebab(name),
      label: ui.label ?? name,
      description: prop.description ?? "",
      kind,
      default: value,
      min: ui.min,
      max: ui.max,
      step: ui.step,
      options: ui.options,
      compileTime: prop.compileTime ?? false,
    };
  });
  catalog.push({
    id: kebab(name),
    component: name,
    label: name.replace(/([a-z])([A-Z])/g, "$1 $2"),
    description: definition.description,
    params,
  });
}
const outputs = [
  [
    "frontend/src/generated/wallpaperShaders.ts",
    `// Generated by scripts/sync-shaders.mjs. Do not edit.\nexport const WALLPAPER_SHADER_DEFINITIONS = ${JSON.stringify(catalog, null, 2)};\n`,
  ],
  [
    "frontend/src/generated/wallpaperShaderLoaders.ts",
    `// Generated by scripts/sync-shaders.mjs. Do not edit.\nexport const WALLPAPER_SHADER_LOADERS = {\n${catalog.map((entry) => `  '${entry.id}': () => import('shaders/core/${entry.component}'),`).join("\n")}\n};\n`,
  ],
];
for (const [path, contents] of outputs) {
  const prettier = require("prettier");
  const formatted = await prettier.format(contents, {
    parser: "typescript",
    ...(await prettier.resolveConfig(resolve(root, path))),
  });
  if (process.argv.includes("--check")) {
    if (readFileSync(resolve(root, path), "utf8") !== formatted)
      throw new Error(`Run just sync-shaders: ${path} is stale`);
  } else writeFileSync(resolve(root, path), formatted);
}
