//! The wire types are declared in Rust and exported as one frontend module.
//! Run `just protocol` after changing a wire type; `cargo test` detects drift.
use ts_rs::TS;

#[test]
fn generated_protocol_is_current() {
    use crate::{
        config::*,
        session::{
            layout::Layout, manager::*, AgentState, AgentStatus, PaneSnapshot, SessionSummary,
        },
        ws::control::*,
    };
    let config = ts_rs::Config::default();
    let declarations = [
        Layout::decl(&config),
        AgentState::decl(&config),
        AgentStatus::decl(&config),
        PaneSnapshot::decl(&config),
        WindowSnapshot::decl(&config),
        SessionSnapshot::decl(&config),
        SessionSummary::decl(&config),
        SessionSort::decl(&config),
        WindowSort::decl(&config),
        Bind::decl(&config),
        Command::decl(&config),
        FontEntry::decl(&config),
        Theme::decl(&config),
        TerminalOptions::decl(&config),
        ClientConfig::decl(&config),
        ConfigUpdate::decl(&config),
        ClientMessage::decl(&config),
        ServerMessage::decl(&config),
        ToastLevel::decl(&config),
        NotificationLevel::decl(&config),
    ];
    let mut output = String::from("// Generated by `just protocol`. Do not edit by hand.\n\n");
    for declaration in declarations {
        output.push_str(&format!("// prettier-ignore\nexport {declaration}\n\n"));
    }
    output.pop(); // exactly one trailing newline, matching prettier
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("frontend/src/generated/protocol.ts");
    if std::env::var_os("BTMUX_UPDATE_PROTOCOL").is_some() {
        std::fs::write(&path, &output).unwrap();
    }
    assert_eq!(
        std::fs::read_to_string(path).unwrap_or_default(),
        output,
        "Run just protocol to regenerate the frontend contract"
    );
}
